//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by spec4.rc
//
#define IDD_DBAR_LEFT_CONTROL           9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_spec4TYPE                   129
#define IDR_MAINFRAME1                  129
#define IDR_MAINFRAME_ACQ               129
#define IDB_BITSPLASH                   130
#define IDR_MAINFRAME_REV               130
#define IDD_SPLASH                      131
#define IDR_OLD_MAINFRAME               131
#define IDD_DIALOG1                     132
#define IDR_OLD_MAINFRAME_ACQ           132
#define IDR_OLD_MAINFRAME_REV           133
#define IDD_DIALOG2                     135
#define IDD_DIALOG3                     136
#define IDD_DBAR_LEFT                   137
#define IDD_DBAR_TOP                    138
#define IDD_DBAR_LEFT1                  139
#define IDD_DBAR_LEFT_ACQ               139
#define IDD_DIALOG4                     140
#define IDD_DIALOG_CUSTINFO             141
#define IDD_DIALOG_PWD                  143
#define IDD_DBAR_LEFT_REV               147
#define IDD_CURSOR                      149
#define IDC_SELECT_GPS                  1001
#define IDC_TEST_GPS                    1002
#define IDC_GPS_NAME                    1003
#define IDC_LATITUDE                    1004
#define IDC_LONGITUDE                   1005
#define IDC_ALTITUDE                    1006
#define IDC_SELECT_SPECTROMETER         1007
#define IDC_TEST_SPECTROMETER           1008
#define IDC_SPECTEST                    1009
#define IDC_EDIT1                       1010
#define IDC_COMBO1                      1011
#define IDC_EDIT2                       1012
#define IDC_SAMPLOC                     1012
#define IDC_BUTTON1                     1013
#define IDC_COMBO2                      1014
#define IDC_BUTTON4                     1014
#define IDC_COMBO3                      1015
#define ID_FRM_SPEC                     1016
#define IDC_EDIT3                       1017
#define IDC_COMBO8                      1017
#define IDC_COMBO4                      1018
#define IDC_COMBO9                      1018
#define IDC_BUTTON2                     1019
#define IDC_EDIT4                       1020
#define IDC_DLG_LEFT_CTRL_ACQ0          1020
#define IDC_COMBO5                      1021
#define IDC_BUTTON3                     1022
#define IDC_COMBO6                      1023
#define IDC_FRM_CAL                     1024
#define IDC_COMBO7                      1025
#define IDC_LIST2                       1027
#define IDC_SUBSEL                      1028
#define IDC_EDIT_ACQTIME                1029
#define IDC_CONC                        1029
#define IDC_BN_ACQ                      1030
#define IDC_EDIT_ACQTIME2               1031
#define IDC_EDIT_ACQAVG                 1031
#define IDC_BN_ACQ_SAVE                 1031
#define IDC_EDIT_ACQTIME3               1032
#define IDC_EDIT_ACQBOXCAR              1032
#define IDC_BN_ACQ_CL                   1033
#define IDC_BN_ACQ_SCAL                 1034
#define IDC_BN_ACQ_BLANK                1035
#define IDC_BN_ACQ_SCAN                 1036
#define IDC_ST_ACQ_CUSTOMER             1037
#define IDC_ST_ACQ_LOC                  1038
#define IDC_GPSLOC                      1038
#define IDC_ST_ACQ_GPS                  1039
#define IDC_ST_ACQ_CN                   1040
#define IDC_ST_ACQ_RES                  1041
#define IDC_PWD                         1041
#define IDC_ST_ACQ_CN_F                 1042
#define IDC_COMPNAME                    1042
#define IDC_ST_ACQ_FN                   1043
#define IDC_SAMPINFO                    1043
#define IDC_ST_ACQ_CN_R                 1044
#define IDC_LOAD                        1044
#define IDC_ST_ACQ_CP                   1045
#define IDC_SAVE                        1045
#define IDC_EDIT_SUBNAME                1046
#define IDC_ST_ACQ_SI                   1047
#define IDC_DLG_LEFT_CTRL_ACQ           1047
#define IDC_DLG_LEFT_CTRL_DEL           1048
#define IDC_DLG_LEFT_CTRL_SAVE          1049
#define IDC_DLG_LEFT_CTRL_LOAD          1050
#define ID_TEXT_FORMULA                 1051
#define ID_TEXT_RSQUARED                1052
#define IDC_DATALIST                    1053
#define IDC_BTN_ADD                     1054
#define IDC_DLG_LEFT_CTRL_SAVE2         1054
#define IDC_DLG_LEFT_CTRL_RESET         1054
#define IDC_BTN_REM                     1055
#define IDC_PIPEKM                      1055
#define IDC_DILUTION                    1056
#define IDC_HIGHLIGHT                   1056
#define IDC_USERDEF                     1057
#define BOUT                            1060
#define IDC_STATIC_ABOUT                1060
#define IDC_ERR_LOW                     1061
#define IDC_CHK_GPS                     1062
#define IDC_WARN_LOW                    1063
#define IDC_CHK_SPEC                    1063
#define IDC_WARN_HIGH                   1064
#define IDC_CHK_AUTOSV1                 1064
#define IDC_ERR_HIGH                    1065
#define IDC_EDIT_PASSWD                 1065
#define IDC_PROGRESS3                   1068
#define IDC_SPLASHIMG                   1070
#define IDC_CUR_WAVLEN                  1071
#define IDC_CUR_COUNTS                  1072
#define IDC_WAVLEN_UP                   1074
#define IDC_CUR_NAME                    1075
#define IDC_SCROLLBAR1                  1080
#define IDC_SCROLLBAR2                  1081
#define ID_TOOLS_OPTIONS                32771
#define ID_COLLECT_SUBSTANCE            32772
#define ID_COLLECT_LOADDEFINITION       32773
#define ID_Menu                         32774
#define ID_COLLECT_LOAD                 32775
#define ID_COLLECT_GPSTOATL             32776
#define ID_COLLECT_ENTERATL             32777
#define ID_COLLECT_SAVE                 32778
#define ID_COLLECT_                     32779
#define ID_COLLECT_MEASURE              32780
#define ID_VIEW_                        32781
#define ID_VIEW_SELECTDATAFILES         32782
#define ID_VIEW_GRAPHTYPE               32783
#define ID_GRAPHTYPE_CONC               32784
#define ID_GRAPHTYPE_CONC32785          32785
#define ID_GRAPHTYPE_LOCATIONONMAP      32786
#define ID_VIEW_SAVEGRAPHINFO           32787
#define ID_VIEW_LOADGRAPHINFO           32788
#define ID_VIEW_EXPORTGRAPH             32789
#define ID_TOOLS_CHANGESETUP            32790
#define ID_TOOLS_SAVESETUP              32791
#define ID_TOOLS_LOAD                   32792
#define ID_TOOLS_CHANGE                 32793
#define ID_TOOLS_SAVE                   32794
#define ID_COLLECT_SAVEATL              32795
#define ID_CALIBRATION_LOADCALIBRATION  32800
#define ID_CALIBRATION_CREATECALIBRATION 32801
#define ID_CALIBRATION_SAVECALIBRATION  32802
#define ID_CALIBRATION_LOAD             32803
#define ID_CALIBRATION_CREATE           32804
#define ID_CALIBRATION_SAVE             32805
#define ID_DLGLFT_S1                    32806
#define ID_DLGLFT_S2                    32807
#define ID_DLGLFT_S3                    32808
#define ID_DLGLFT_S4                    32809
#define ID_DLGLFT_S5                    32810
#define ID_CONTROLMODE_SWITCHTOACQUISITION 32814
#define ID_CONTROLMODE_SWITCH           32815
#define ID_GRAPHTYPE_CALIBRATIONSPECTRA 32816
#define ID_GRAPHTYPE_CALIBRATIONSPECTRA32817 32817
#define ID_GRAPHTYPE_CURRENTACQUISITION 32818
#define ID_GRAPHTYPE_CURRENTACQUISITION32819 32819
#define ID_REVIEWMODE_SWITCHTOACQUISITION 32820
#define ID_MODESET_CONTROL              32821
#define ID_MODESET_ACQ                  32822
#define ID_ACQUISITIONMODE_SWITCHTOREVIEW 32823
#define ID_MODESET                      32824
#define ID_MODESET_REV                  32825
#define ID_CONTROLMODE_SWITCHTOREVIEW   32826
#define ID_Menu32827                    32827
#define ID_GRAPHTYPE_REVSPEC            32828
#define ID_CONTROLMODE_SWITCHTOCONTROL  32829
#define ID_ITEM_DUMMY                   32830
#define ID_MENU_DUMMY                   32831
#define ID_REVIEWMODE_SWITCHTOREVIEW    32832
#define ID_DLGLFT_CTRL_F1               32833
#define ID_DLGLFT_CTRL_F2               32834
#define ID_DLGLFT_CTRL_F3               32835
#define ID_DLGLFT_CTRL_F4               32836
#define ID_DLGLFT_CTRL_F                32837
#define ID_DLGLFT_CTRL_F5               32837
#define ID_VIEW_DATASPECTRUM            32838
#define ID_DATASPECTRUM_BASELINE        32839
#define ID_DATASPECTRUM_RAW             32840
#define ID_DATASPECTRUM_DATA            32841
#define ID_DSV_BASELINE                 32842
#define ID_DSV_RAW                      32843
#define ID_DSV_DATA                     32844
#define ID_GRAPHTYPE_REPORT             32845
#define ID_VIEW_CURSOR                  32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
